FROM registry.fedoraproject.org/fedora-toolbox:latest
ENV TERM=xterm-256color

RUN dnf -y install \
	bat \
	zsh \
	neovim \
	llvm \
	lldb \
	clang \
	fd-find \
	git-delta \
	gh \
	ripgrep \
	fzf \
	tmux \
	inotify-tools
