# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 1000

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[container]
disabled=true
style = "bold blue dimmed"

[custom.toolbox]
command = ". /run/.containerenv && echo $name"
when = "cat /run/.containerenv"
style = "bold blue"
format = "in [($output)]($style) "
