format = '$all$custom$character'

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = true

[container]
disabled = true
format = '[$symbol \[$name\]]($style) '
symbol = '󰡨'
style = 'bold cyan dimmed'

[custom.distrobox]
command = ''' grep -oP '(?<=\bname=")[^";]+' /run/.containerenv '''
when = 'find /run/.containerenv'
symbol = '󰡨'
format = '[$symbol \[$output\]]($style) '
style = 'bold cyan dimmed'
