FROM registry.fedoraproject.org/fedora-toolbox:38
ENV TERM=xterm-256color

RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/conmon
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/crun
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open

RUN dnf update -y
RUN dnf install -y dnf-plugins-core
RUN dnf copr enable -y atim/starship
RUN dnf copr enable -y varlad/zellij
RUN dnf group install -y 'C Development Tools and Libraries' 'Development Tools'

RUN dnf -y install \
  starship \
  zellij \
	bat \
	zsh \
	neovim \
	llvm \
	lldb \
	clang \
	fd-find \
	git-delta \
	gh \
	ripgrep \
	fzf \
	tmux \
	inotify-tools
