FROM registry.fedoraproject.org/fedora-toolbox:38
ENV TERM=xterm-256color

RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/conmon
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/crun
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker
RUN ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker-compose

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
RUN sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

RUN dnf update -y
RUN dnf install -y dnf-plugins-core
RUN dnf copr enable -y atim/starship
RUN dnf copr enable -y varlad/zellij
RUN dnf group install -y 'C Development Tools and Libraries' 'Development Tools'

RUN dnf -y install \
	code \
	starship \
	zellij \
	bat \
	zsh \
	neovim \
	llvm \
	lldb \
	clang \
	fd-find \
	git-delta \
	gh \
	ripgrep \
	fzf \
	tmux \
	inotify-tools
