provider = "docker"
dotfiles = [
	".zshenv",
	".config/zsh/",
	".config/nvim/init.lua",
	".config/nvim/lua/",
	".config/helix/",
	".config/tmux/",
	".config/zellij/",
	".config/gh/",
	".config/starship.toml"
]

